my_dbt_project:  # <-- should match `project.yml` name
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dbt_user
      password: dbt_pass
      port: 5432
      dbname: dbt_db
      schema: public  # You can change to anything; this is where models will go
      threads: 4
      keepalives_idle: 0
      sslmode: prefer
